# HTTP Configuration
quarkus.http.port=8080

# Database Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/reservation
quarkus.datasource.username=postgres
quarkus.datasource.password=admin

# Hibernate Configuration
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# RabbitMQ Configuration
rabbitmq-host=localhost
rabbitmq-port=5672
rabbitmq-username=guest
rabbitmq-password=guest

# RabbitMQ Connector
mp.messaging.connector.smallrye-rabbitmq.host=localhost
mp.messaging.connector.smallrye-rabbitmq.port=5672
mp.messaging.connector.smallrye-rabbitmq.username=guest
mp.messaging.connector.smallrye-rabbitmq.password=guest

# Outgoing channel for reserve created events
mp.messaging.outgoing.reserve-created.connector=smallrye-rabbitmq
mp.messaging.outgoing.reserve-created.exchange.name=reserve-events
mp.messaging.outgoing.reserve-created.routing-keys=reserve.created

